-- Show only countries that have more than 1000 titles
-- SELECT country, count(*) as Total_Contents
-- From netflix_titles_exploded
-- where country != 'Unknown'
-- group by country
-- having count(*) > 1000
-- order by total_contents DESC
-- limit 10;

-- Show only directors who have more than 5 titles on Netflix, ordered from highest to lowest
-- SELECT director , count(*) as Total_Titles
-- from netflix_titles_exploded
-- where director != 'Unknown'
-- group by director
-- having count(*) >100
-- order by Total_Titles DESC
-- limit 10;

-- categorize Netflix titles into Classic and Modern
-- SELECT
--     title,
--     [Release Year],
--     CASE
--         WHEN [Release Year] >= 2015 THEN 'Modern'
--         ELSE 'Classic'
--     END AS content_era
-- FROM netflix_titles;

-- Categorize movie lengths (Short, Medium, Long)
-- SELECT title,
-- [Release Year],
-- Case
--     When CAST(Replace (duration, ' min', '') AS INT) <= 60 Then 'Short'
--     When CAST(Replace (duration, ' min', '') AS INT) >= 61 and CAST(Replace (duration, ' min', '') AS INT) <= 120 then 'Medium'
--     When CAST(Replace (duration, ' min', '') AS INT) >= 121 then 'Long' 
--     Else 'Unknown'
-- End as Movie_length
-- From netflix_titles_exploded
-- where type = 'Movie'
-- order by [Movie_length] ;

-- Categorize ratings (Kids, Teens, Adults, unrated, Kids/Family)
-- SELECT title, [Release Year],
-- Rating,
-- CASE
--     WHEN rating IN ('G', 'Tv-Y', 'TV-G', 'Tv-Y7') THEN 'Kids'
--     WHEN rating IN ('Pg-13', 'Tv-14', 'Tv-Pg') THEN 'Teens'
--     WHEN rating IN ('R', 'Nc-17', 'Tv-Ma') THEN 'Adults'
--     when rating IN ('Pg') THEN 'Kids/Family'
--     WHEN rating IN ('Ur', 'Nr') THEN 'Unrated'
--     ELSE 'Unknown'
-- END AS Rating_Category
-- from netflix_titles_exploded
-- where rating != 'Unknown'
-- order by [Rating_Category] ;

-- Count total number of titles in each rating category
-- with rating_counts as (
--     SELECT title, [Release Year],
-- Rating,
-- CASE
--     WHEN rating IN ('G', 'Tv-Y', 'TV-G', 'Tv-Y7') THEN 'Kids'
--     WHEN rating IN ('Pg-13', 'Tv-14', 'Tv-Pg') THEN 'Teens'
--     WHEN rating IN ('R', 'Nc-17', 'Tv-Ma') THEN 'Adults'
--     when rating IN ('Pg') THEN 'Kids/Family'
--     WHEN rating IN ('Ur', 'Nr') THEN 'Unrated'
--     ELSE 'Unknown'
-- END AS Rating_Category
-- from netflix_titles_exploded
-- where rating != 'Unknown'
-- order by [Rating_Category]
-- )
-- Select Rating_Category, count(*) as Total_Titles
-- from rating_counts
-- group by Rating_Category
-- order by Total_Titles DESC;

-- Count total number of titles in each content era
-- with content_era_counts as (
-- SELECT
--     title,
--     [Release Year],
--     CASE
--         WHEN [Release Year] >= 2015 THEN 'Modern'
--         ELSE 'Classic'
--     END AS content_era
-- FROM netflix_titles
-- )
-- Select content_era, count(*) as Total_Titles
-- from content_era_counts
-- group by content_era
-- order by Total_Titles DESC;

-- Count total number of titles in each Movie length category
-- with movie_length_counts as (
-- SELECT title,
-- [Release Year],
-- Case
--     When CAST(Replace (duration, ' min', '') AS INT) <= 60 Then 'Short'
--     When CAST(Replace (duration, ' min', '') AS INT) >= 61 and CAST(Replace (duration, ' min', '') AS INT) <= 120 then 'Medium'
--     When CAST(Replace (duration, ' min', '') AS INT) >= 121 then 'Long'
--     Else 'Unknown'
-- End as Movie_length
-- From netflix_titles_exploded
-- where type = 'Movie'
-- order by [Movie_length]
-- )
-- select Movie_length, count(*) as Total_Titles
-- from movie_length_counts
-- group by Movie_length
-- order by Total_Titles DESC;


